### PR TITLE
Padding options

### PR DESCRIPTION
**Pull request by jallier**
Hi, I have added options for padding the date/time on insert.

### CODE REVIEW

**Comment by dannyfritz** [comment]
If I'm understanding the code, this creates a new line, and matches the indentation of the last line before inserting a date?

**Comment by jallier** [comment]
Not quite. It just adds a padding character that matches the length of the inserted date. For example, if you inserted the date 17/07/16, and the padding character was #, the result would be:
#######
17/07/16
#######
Unchecking the checkboxes will insert the entire padding string rather than just the first char for either pre or post padding. If the padding string is left blank nothing will be inserted for pre/post. 

It's just something I use the package for, and I thought it would be useful if it could automatically match the length of the date string.

**Comment by jallier** [comment]
Also just realized I had a small typo in the title for postPaddingMatchLength. Fixed

**Comment by dannyfritz** [comment]
Thanks for the PR!
However, I feel that this adds a lot of complexity to the code that I don't wish to maintain. I recommend you create a package named `date-plus` and reimplement the functionality of `date` or use `date` as a dependency and call the commands `date` provides.

**Comment by jallier** [comment]
No worries, i'll do that then. Thanks!

**Pull request closed without merging**
