### PR TITLE
update to use new config format

### LINKED ISSUE #7: Uncaught TypeError: Cannot read property '0' of undefined
[Enter steps to reproduce below:]

1. ...just tried using the package and exception appreared. 
2. ...

**Atom Version**: 1.1.0
**System**: Microsoft Windows 7 Home Premium 
**Thrown From**: [date](https://github.com/dannyfritz/atom-date) package, v1.1.0

### Stack Trace

Uncaught TypeError: Cannot read property '0' of undefined

```
At C:\Users\ngunyi\.atom\packages\date\node_modules\date-utils\lib\date-utils.js:1429

TypeError: Cannot read property '0' of undefined
  at toFormat (C:\Users\ngunyi\.atom\packages\date\node_modules\date-utils\lib\date-utils.js:1429:53)
  at Date.toFormat (C:\Users\ngunyi\.atom\packages\date\node_modules\date-utils\lib\date-utils.js:1360:16)
  at get (C:\Users\ngunyi\.atom\packages\date\lib\date.js:34:20)
  at atom-text-editor.dateDate (C:\Users\ngunyi\.atom\packages\date\lib\date.js:9:12)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\ngunyi\AppData\Local\atom\app-1.1.0\resources\app.asar\src\command-registry.js:243:29)
  at C:\Users\ngunyi\AppData\Local\atom\app-1.1.0\resources\app.asar\src\command-registry.js:3:61
  at CommandPaletteView.module.exports.CommandPaletteView.confirmed (C:\Users\ngunyi\AppData\Local\atom\app-1.1.0\resources\app.asar\node_modules\command-palette\lib\command-palette-view.js:159:32)
  at CommandPaletteView.module.exports.SelectListView.confirmSelection (C:\Users\ngunyi\AppData\Local\atom\app-1.1.0\resources\app.asar\node_modules\atom-space-pen-views\lib\select-list-view.js:338:21)
  at space-pen-li.<anonymous> (C:\Users\ngunyi\AppData\Local\atom\app-1.1.0\resources\app.asar\node_modules\atom-space-pen-views\lib\select-list-view.js:139:19)
  at HTMLOListElement.jQuery.event.dispatch (C:\Users\ngunyi\AppData\Local\atom\app-1.1.0\resources\app.asar\node_modules\jquery\dist\jquery.js:4435:9)
  at HTMLOListElement.elemData.handle (C:\Users\ngunyi\AppData\Local\atom\app-1.1.0\resources\app.asar\node_modules\jquery\dist\jquery.js:4121:28)

```

### Commands

```
 19x -4:35.5.0 core:delete (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
     -4:30.3.0 autocomplete-plus:confirm (atom-text-editor.editor.vim-mode.insert-mode.is-focused.autocomplete-active)
     -4:29.5.0 editor:newline (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
 17x -4:28.7.0 core:backspace (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
     -3:48.3.0 command-palette:toggle (atom-text-editor.editor.vim-mode.insert-mode.autocomplete-active.is-focused)
     -3:47 application:minimize (atom-text-editor.editor.vim-mode.insert-mode.autocomplete-active)
     -3:42.4.0 command-palette:toggle (atom-text-editor.editor.vim-mode.insert-mode.autocomplete-active.is-focused)
  6x -3:39.9.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -3:34 date:date (atom-text-editor.editor.vim-mode.insert-mode.autocomplete-active)
  2x -3:03.2.0 command-palette:toggle (ul.list-inline.tab-bar.inset-panel)
     -2:51.5.0 date:date (atom-text-editor.editor.vim-mode.insert-mode.autocomplete-active)
 17x -2:03.3.0 core:backspace (atom-text-editor.editor.vim-mode.insert-mode.autocomplete-active.is-focused)
     -2:00.5.0 command-palette:toggle (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
     -1:55.5.0 date:time (atom-text-editor.editor.vim-mode.insert-mode)
     -0:25.4.0 command-palette:toggle (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
     -0:15.6.0 date:date (atom-text-editor.editor.vim-mode.insert-mode)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "vim-mode-plus"
    ]
  }
}
```

### Installed Packages

```coffee
# User
date, v1.1.0
markdown-table-formatter, v2.5.4
markdown-writer, v2.0.1
vim-mode, v0.62.0

# Dev
No dev packages
```

### PR DESCRIPTION
**Pull request by spencerlyon2**
closes #7

### CODE REVIEW

**Comment by memerelics** [comment]
:+1:

**Comment by adius** [comment]
@dannyfritz A merge would be appreciated! =P

**Comment by dannyfritz** [comment]
Sometimes i wonder how i miss these things in GitHub. I'll take a look within 2 hours and make a decision. :smile:

**Comment by adius** [comment]
Haha, I know this problem. =P
Thanks for merging!

**Comment by dannyfritz** [comment]
It isn't merged. :P I'm looking at it starting now.

**Comment by dannyfritz** [comment]
Thanks for the PR @spencerlyon2. Merging!

**Comment by spencerlyon2** [comment]
No problem!




// Spencer

On November 7, 2015 at 12:41:09 PM, Danny Fritz (notifications@github.com) wrote:

Thanks for the PR @spencerlyon2. Merging!

**Pull request merged**
